/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.dao.Ireimbursement;
import com.revature.dao.Iuser;
import com.revature.dao.reimbursementJDBC;
import com.revature.dao.userJDBC;
import com.revature.models.Reimbursement;
import com.revature.services.UserService;

import java.time.LocalDate;


public class MainDriver {

    public static void main(String[] args) {

        Iuser ud = new userJDBC();
        UserService us = new UserService(ud);


        LocalDate myDate = LocalDate.now();
        Reimbursement r1 = new Reimbursement(3200, myDate, "Stayed in hotel", 1);
        r1.toString();
        System.out.print(r1.toString());

        Ireimbursement createTest = new reimbursementJDBC();

        createTest.employeeCreateReimbursment(r1);
    }

}